#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
wd() {
  . ~/bin/wd/wd.sh
}

alias ll="ls -altrh"

# now vim can use !s and !q
alias vim="stty stop '' -ixoff ; vim"
ttyctl -f

# remap caps to ESC
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
wd() {
  . ~/bin/wd/wd.sh
}
